name: Build and Auto-Publish

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'microsoft'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build mod
        run: ./gradlew build

      # 1
      - name: Extract mod version
        id: get_version
        run: |
          # reading mod_version=... from gradle.properties
          VERSION=$(grep -i "mod_version" gradle.properties | cut -d'=' -f2 | tr -d ' \r')
          echo "MOD_VERSION=$VERSION" >> $GITHUB_ENV

      # 2
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ env.MOD_VERSION }}-b${{ github.run_number }}"
          name: "Release v${{ env.MOD_VERSION }} (Build #${{ github.run_number }})"
          body: |
            auto build for commit `${{ github.sha }}`.
            commit msg: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
          files: build/libs/!(*-@(dev|sources|javadoc)).jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
